ISW2PDT5/Controllers/CategoriaProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISW2PDT5.Controllers
{
    public class CategoriaProductoController : Controller
    {
        private mydbEntities db = new mydbEntities();

        //
        // GET: /CategoriaProducto/

        public ActionResult Index()
        {
            return View(db.categoria_producto.ToList());
        }

        //
        // GET: /CategoriaProducto/Details/5

        public ActionResult Details(int id = 0)
        {
            categoria_producto categoria_producto = db.categoria_producto.Find(id);
            if (categoria_producto == null)
            {
                return HttpNotFound();
            }
            return View(categoria_producto);
        }

        //
        // GET: /CategoriaProducto/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CategoriaProducto/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(categoria_producto categoria_producto)
        {
            if (ModelState.IsValid)
            {
                db.categoria_producto.Add(categoria_producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria_producto);
        }

        //
        // GET: /CategoriaProducto/Edit/5

        public ActionResult Edit(int id = 0)
        {
            categoria_producto categoria_producto = db.categoria_producto.Find(id);
            if (categoria_producto == null)
            {
                return HttpNotFound();
            }
            return View(categoria_producto);
        }

        //
        // POST: /CategoriaProducto/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(categoria_producto categoria_producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria_producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoria_producto);
        }

        //
        // GET: /CategoriaProducto/Delete/5

        public ActionResult Delete(int id = 0)
        {
            categoria_producto categoria_producto = db.categoria_producto.Find(id);
            if (categoria_producto == null)
            {
                return HttpNotFound();
            }
            return View(categoria_producto);
        }

        //
        // POST: /CategoriaProducto/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            categoria_producto categoria_producto = db.categoria_producto.Find(id);
            db.categoria_producto.Remove(categoria_producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ISW2PDT5/Controllers/SeccionesBodegaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISW2PDT5.Controllers
{
    public class SeccionesBodegaController : Controller
    {
        private mydbEntities db = new mydbEntities();

        //
        // GET: /SeccionesBodega/

        public ActionResult Index()
        {
            return View(db.seccion_bodega.ToList());
        }

        //
        // GET: /SeccionesBodega/Details/5

        public ActionResult Details(int id = 0)
        {
            seccion_bodega seccion_bodega = db.seccion_bodega.Find(id);
            if (seccion_bodega == null)
            {
                return HttpNotFound();
            }
            return View(seccion_bodega);
        }

        //
        // GET: /SeccionesBodega/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SeccionesBodega/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(seccion_bodega seccion_bodega)
        {
            if (ModelState.IsValid)
            {
                db.seccion_bodega.Add(seccion_bodega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seccion_bodega);
        }

        //
        // GET: /SeccionesBodega/Edit/5

        public ActionResult Edit(int id = 0)
        {
            seccion_bodega seccion_bodega = db.seccion_bodega.Find(id);
            if (seccion_bodega == null)
            {
                return HttpNotFound();
            }
            return View(seccion_bodega);
        }

        //
        // POST: /SeccionesBodega/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(seccion_bodega seccion_bodega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seccion_bodega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seccion_bodega);
        }

        //
        // GET: /SeccionesBodega/Delete/5

        public ActionResult Delete(int id = 0)
        {
            seccion_bodega seccion_bodega = db.seccion_bodega.Find(id);
            if (seccion_bodega == null)
            {
                return HttpNotFound();
            }
            return View(seccion_bodega);
        }

        //
        // POST: /SeccionesBodega/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            seccion_bodega seccion_bodega = db.seccion_bodega.Find(id);
            db.seccion_bodega.Remove(seccion_bodega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ISW2PDT5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>GASISW - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/footable.core.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/footable.metro.css" />   
</head>
<body>
    <!-- Navegador Superior -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">GASISW</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-user fa-2x"></span> Baltazar Lopez
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Perfil</a></li>
                            <li><a href="#"><span class="fa fa-sign-out fa-2x"></span> Cerrar Sesion</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2">
                <div id="accordion" class="panel-group">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#Mantenimientos">
                                    <span class="fa fa-pencil fa-2x"></span>Mantenimientos
                                </a>
                            </h4>
                        </div>
                        <div id="Mantenimientos" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul class="nav nav-stacked">
                                    <li>@Html.ActionLink("Secciones de Bodega", "Index", "SeccionesBodega")</li>
                                    <li>@Html.ActionLink("Categorias de Productos", "Index", "CategoriaProducto")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Departamento", "Index", "Departamento")</li>
                                    <li>@Html.ActionLink("Municipio", "Index", "Municipio")</li>
                                    <li>@Html.ActionLink("Sucursal", "Index", "Sucursal")</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#Procesos">
                                    <span class="fa fa-exchange fa-2x"></span>Procesos
                                </a>
                            </h4>
                        </div>
                        <div id="Procesos" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Aqui iran los Procesos</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#Consultas">
                                    <span class="fa fa-search fa-2x"></span>Consultas y Reportes
                                </a>
                            </h4>
                        </div>
                        <div id="Consultas" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Aqui iran las Consultas y los Reportes</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#Opciones">
                                    <span class="fa fa-cog fa-2x"></span>Opciones del Sistema
                                </a>
                            </h4>
                        </div>
                        <div id="Opciones" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Aqui iran las Consultas y los Reportes</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-10">
                @RenderBody()
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <footer>Universidad Francisco Gavidia | Ingenieria del Software 2 | Grupo 1 | 2015</footer>
            </div>
        </div>
    </div>   

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/footable.js"></script>
    <script type="text/javascript" src="~/Scripts/footable.paginate.js"></script>
    <script type="text/javascript" src="~/Scripts/footable.sort.js"></script>
    <script type="text/javascript" src="~/Scripts/footable.filter.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        $("table").footable();
    });
    </script>
</body>
</html>

ISW2PDT5/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>GASISW - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.css" />
    @*<link type="text/css" rel="stylesheet" href="~/Content/footable.core.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/footable.standalone.css" />*@
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="text-primary">SISTEMA DE CONTROL DE INVENTARIO Y FACTURACIÓN PARA ESTACIÓN DE SERVICIO EN DESPACHO DE COMBUSTIBLE Y TIENDA DE PRODUCTOS</h1>
            </div>
        </div>
        <div class="row">
                @RenderBody()
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <footer>Universidad Francisco Gavidia | Ingenieria del Software 2 | Grupo 1 | 2015</footer>
            </div>
        </div>
    </div>   

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>